# Generated by Django 2.0.6 on 2018-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180621_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='blog.Tag'),
        ),
    ]
